version: "3"
services:
  express-boiler-plate:
    container_name: express-boiler-plate
    image: express-boiler-plate
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DOCKER_ENV_VAR: "Test Worked fine!"
    networks:
      - dockernet

networks:
  dockernet:
    external:
      name: dockernet
